import { NextRequest }  from 'next/server'
import { auth }          from '@/auth'
import { serverApiBase } from '@/lib/api/client'
import { getAnalysisResult } from '@/lib/api/analyze.api'
import type { ChatRequest }  from '@/types/chat.types'
import type { PipelineResult } from '@/types/analysis.types'

// ── OpenAI streaming ──────────────────────────────────────────────────────────
// We call the OpenAI REST API directly with fetch() so this route stays
// compatible with Next.js Edge Runtime (no SDK needed).
const OPENAI_URL   = 'https://api.openai.com/v1/chat/completions'
const OPENAI_MODEL = 'gpt-4o'

// ── System prompt builder ─────────────────────────────────────────────────────

/**
 * Builds a focused system prompt from:
 * - Structural analysis (PipelineResult)
 * - A bounded raw source "pack" for the user-selected paths
 *
 * The raw source pack is generated by the backend on demand (it may re-clone
 * the repo for GitHub analyses). The pack is byte-capped and may truncate files.
 */
function buildSystemPrompt(args: {
  result: PipelineResult
  selectedPaths: string[]
  sourcePack: {
    rootHint: string
    totalTokens: number
    files: { path: string; truncated: boolean; content: string }[]
  }
}): string {
  const { result, selectedPaths, sourcePack } = args
  const { projectName, detection, metrics, smells } = result
  const lang      = detection.languages[0]?.name ?? 'unknown'
  const framework = detection.framework ?? 'none'

  const scopeLabel = selectedPaths.length > 0 ? selectedPaths.join(', ') : 'no source scope selected'
  const smellsPreview = smells
    .slice(0, 20)
    .map((s) => `- [${s.severity.toUpperCase()}] ${s.type}${s.module ? ` (${s.module})` : ''}: ${s.message}`)
    .join('\n') || '- none'

  const filesBlock = sourcePack.files.length === 0
    ? '(no source files returned — select at least one folder like "src/auth")'
    : sourcePack.files.map((f) => {
        const trunc = f.truncated ? ' (TRUNCATED)' : ''
        return `--- file: ${f.path}${trunc} ---\n${f.content}\n`
      }).join('\n')

  return `You are a senior software engineer helping the user understand and improve the codebase "${projectName}".

SCOPE: Answer ONLY about the following modules/files: ${scopeLabel}
If the user asks about something outside this scope, politely say you only have context for the listed modules and suggest they add those files to the context.

PROJECT CONTEXT:
- Language: ${lang}
- Framework: ${framework}
- ORM: ${detection.orm ?? 'none'}
- Analysis depth: ${detection.analysisDepth}
- Source root: ${sourcePack.rootHint}

ARCHITECTURE METRICS (full project):
- Module count: ${metrics.moduleCount}
- Dependency count: ${metrics.dependencyCount}
- Cycle count: ${metrics.cycleCount}
- Average fan-out: ${metrics.averageFanOut}
- Max fan-out: ${metrics.maxFanOut}
- Dependency density: ${(metrics.dependencyDensity * 100).toFixed(1)}%

ARCHITECTURE SMELLS (top 20 preview):
${smellsPreview}

INSTRUCTIONS:
1. Use the SOURCE FILES below as ground truth. If they are truncated or insufficient, ask the user to add more paths to scope.
2. Be specific — mention file paths and function/class names when relevant.
3. When identifying issues, explain WHY they are a problem and HOW to fix them (with minimal, safe edits).
4. Format code suggestions in fenced code blocks with the correct language tag.
5. Do not request or output secrets. Never invent code that is not present in SOURCE FILES.

SOURCE FILES (selected scope, ~${sourcePack.totalTokens} tokens):
${filesBlock}` 
}

// ── Route handler ─────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  const session = await auth()
  if (!session?.accessToken) {
    return new Response('Unauthorized', { status: 401 })
  }

  const apiKey = process.env.OPENAI_API_KEY
  if (!apiKey) {
    return new Response('OpenAI API key not configured', { status: 503 })
  }

  let body: ChatRequest
  try {
    body = await req.json() as ChatRequest
  } catch {
    return new Response('Invalid JSON', { status: 400 })
  }

  const { jobId, messages, selectedIds } = body

  if (!jobId || !Array.isArray(messages)) {
    return new Response('jobId and messages are required', { status: 400 })
  }

  // Fetch the analysis result to build the system prompt
  let result: PipelineResult
  try {
    result = await getAnalysisResult(jobId, session.accessToken)
  } catch {
    return new Response('Analysis result not found — it may have expired', { status: 404 })
  }

  const selectedPaths = (selectedIds ?? []).filter((id) => id !== '__overview__')

  // Fetch raw source pack for the selected paths (bounded, may truncate)
  const base = serverApiBase()
  const packRequestBody = JSON.stringify({
    paths: selectedPaths,
    includeImportClosure: true,
    importDepth: 2,
    maxTotalBytes: 220000,
    maxFileBytes: 45000,
    maxFiles: 60,
  })
  const authHeaders: Record<string, string> = {
    'Content-Type': 'application/json',
  }
  if (session.accessToken) {
    authHeaders.Authorization = `Bearer ${session.accessToken}`
  }

  let packRes = await fetch(`${base}/copilot/${jobId}/source-pack`, {
    method: 'POST',
    headers: authHeaders,
    body: packRequestBody,
  })

  // Fallback for backends that expose source-pack under /analyze.
  if (!packRes.ok) {
    const analyzePackRes = await fetch(`${base}/analyze/${jobId}/source-pack`, {
      method: 'POST',
      headers: authHeaders,
      body: packRequestBody,
    })
    if (analyzePackRes.ok) {
      packRes = analyzePackRes
    }
  }

  const sourcePack = await packRes.json().catch(() => null) as null | {
    rootHint: string
    totalTokens: number
    files: { path: string; truncated: boolean; content: string }[]
  }

  const resolvedSourcePack = (!packRes.ok || !sourcePack)
    ? {
        rootHint: 'unavailable',
        totalTokens: 0,
        files: [] as { path: string; truncated: boolean; content: string }[],
      }
    : sourcePack

  const systemPrompt = buildSystemPrompt({
    result,
    selectedPaths,
    sourcePack: resolvedSourcePack,
  })

  // Call OpenAI with streaming enabled
  const openaiRes = await fetch(OPENAI_URL, {
    method:  'POST',
    headers: {
      'Content-Type':  'application/json',
      'Authorization': `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model:       OPENAI_MODEL,
      stream:      true,
      max_tokens:  1024,
      temperature: 0.3,   // lower = more precise for technical answers
      messages: [
        { role: 'system', content: systemPrompt },
        ...messages.map((m) => ({ role: m.role, content: m.content })),
      ],
    }),
  })

  if (!openaiRes.ok || !openaiRes.body) {
    const err = await openaiRes.text()
    console.error('[POST /api/chat] OpenAI error:', err)
    return new Response('OpenAI request failed', { status: 502 })
  }

  // Transform the OpenAI SSE stream (data: {...}) → plain text stream
  // so the client hook can simply accumulate raw text chunks
  const encoder = new TextEncoder()
  const readable = new ReadableStream({
    async start(controller) {
      const reader  = openaiRes.body!.getReader()
      const decoder = new TextDecoder()
      let buffer = ''

      try {
        while (true) {
          const { done, value } = await reader.read()
          if (done) break

          buffer += decoder.decode(value, { stream: true })
          const lines = buffer.split('\n')
          buffer = lines.pop() ?? ''

          // OpenAI streams lines like: data: {"choices":[{"delta":{"content":"..."}}]}
          for (const line of lines) {
            const trimmed = line.trim()
            if (!trimmed.startsWith('data:')) continue
            const json = trimmed.slice(5).trim()
            if (json === '[DONE]') continue

            try {
              const parsed = JSON.parse(json) as {
                choices?: { delta?: { content?: string } }[]
              }
              const text = parsed.choices?.[0]?.delta?.content
              if (text) controller.enqueue(encoder.encode(text))
            } catch {
              // Skip malformed complete lines. Partial lines are preserved in `buffer`.
            }
          }
        }

        // Flush any final complete line that arrived without trailing newline.
        const finalLine = buffer.trim()
        if (finalLine.startsWith('data:')) {
          const json = finalLine.slice(5).trim()
          if (json && json !== '[DONE]') {
            try {
              const parsed = JSON.parse(json) as {
                choices?: { delta?: { content?: string } }[]
              }
              const text = parsed.choices?.[0]?.delta?.content
              if (text) controller.enqueue(encoder.encode(text))
            } catch {
              // Ignore incomplete tail.
            }
          }
        }
      } finally {
        controller.close()
      }
    },
  })

  return new Response(readable, {
    headers: {
      'Content-Type':  'text/plain; charset=utf-8',
      'Cache-Control': 'no-cache',
      'X-Accel-Buffering': 'no',
    },
  })
}
